### ISSUE TITLE
No such glyph 0xFB01

### ISSUE THREAD

**Issue by ronpandolfi** [powerline/fontpatcher#19]
When trying to patch the font linked (Commodore 64) below, I get 

```
Traceback (most recent call last):
  File "powerline-fontpatcher", line 144, in <module>
    raise SystemExit(main(sys.argv[1:]))
  File "powerline-fontpatcher", line 141, in main
    return patch_fonts(args.source_font, args.target_fonts, args.rename_font)
  File "powerline-fontpatcher", line 133, in patch_fonts
    patch_one_font(source_font, target_font, rename_font)
  File "powerline-fontpatcher", line 117, in patch_one_font
    target_font[0xFB01].removePosSub('*')  # fi ligature
TypeError: No such glyph
```

Can you point me in the right direction?

https://www.dropbox.com/s/23crhkwdyhi33is/C64_Pro_Mono_v1.0-STYLE.ttf?dl=0

**Comment by smokku** [comment]
You can do instead:

- Launch `fontforge`
- Open your font
- Select menu: _Element -> Merge Fonts..._ and open `fonts/powerline-symbols.sfd`
- Select _File -> Generate Fonts..._ and save your font somewhere

Done.
